[build-system]
requires = ["flit_core >=3.2,<4","opencv-python"]
build-backend = "flit_core.buildapi"

[project]
name = "ziku"
authors = [{name = "zhaomingming", email = "13271929138@163.com"}]
dynamic = ["version", "description"]
